services:
  lta.webapi:
    container_name: loginet-web-api
    image: lta.webapi
    environment:
      ApplicationSettings__DatabaseAddress: "postgres-database"
      ApplicationSettings__DatabaseName: "test_database"
      ApplicationSettings__DatabaseUser: "admin"
      ApplicationSettings__DatabasePassword: "admin"
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: src/LTA.WebAPI/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-tier
      - back-tier
  postgres:
    container_name: postgres-database
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "test_database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - back-tier

networks:
  front-tier:
    name: front-tier
    driver: bridge
  back-tier:
    name: back-tier
    driver: bridge